development:
  password: shptka_18b0cc7bc2b4e76c218774cd8d6ba6c9
  theme_id: "163911139626"
  store: andrewbaklytsky.myshopify.com
  ignore_files:
#    - config/settings_data.json
#    - templates/*.json



#development:
#  password: shptka_b12d28e86915fe08adb1a5a165401d88
#  theme_id: "163725181211"
#  store: andrewbaklytsky2.myshopify.com
#  ignore_files:
#    - config/settings_data.json
#    - templates/*.json